name: Build and Push
run-name: Build and Push to dist/${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      pack_root:
        description: 'Pack root content into npm tarball'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Pack and extract root content into npm tarball
      if: ${{ inputs.pack_root }}
      run: |
        tarball_name=$(npm pack)
        mkdir -p .tarball
        tar -xvf $tarball_name -C .tarball

    - name: Upload artifact with tarball content
      if: ${{ inputs.pack_root }}
      uses: actions/upload-artifact@v3
      with:
        name: tmp
        path: .tarball/package

    - name: Upload dist artifact
      if: ${{ !inputs.pack_root }}
      uses: actions/upload-artifact@v3
      with:
        name: tmp
        path: dist

  push:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare
      run: |
        git checkout --orphan dist/${{ github.ref_name }}
        git config --local user.email rete-js[bot]@users.noreply.github.com
        git config --local user.name rete-js[bot]
        git rm -rf .

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: tmp
        path: .

    - name: Commit changes
      run: |
        git add .
        git commit -m "build: upload dist"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dist/${{ github.ref_name }}
