name: Update docs

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
          repository: retejs/retejs.org
      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Update .typedoc
        run: |
          echo "# TODO replace .typedoc file for ${{ inputs.package }}"
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          author: rete-js[bot] <rete-js[bot]@users.noreply.github.com>
          commit-message: Update API docs for ${{ inputs.package }}
          title: Update API docs for ${{ inputs.package }}
          branch: api-docs-${{ inputs.package }}
